# Read the documentation: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/doc/setup.md
fos_elastica:
    clients:
        default: { url: '%env(ELASTICSEARCH_URL)%' }
    indexes:
        app:
            persistence:
                driver: orm
                model: App\Entity\Article
                elastica_to_model_transformer:
                    query_builder_method: createQueryBuilderForElastica

            properties:
                title: { type: text }
                caption: { type: text }
                text: { type: text }
                category:
                    property_path: getCategoryName
                tags:
                    type: object
                    properties:
                        name:
                            type: keyword
